### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth":"2022-03-26",
  "email" : "eumseo@icloud.com",
  "name" : "Test",
  "password" : "1234",
  "phone" : "01000000000"
}
### 로그인 (고객)
POST http://localhost:8081/signIn/customer
Content-Type: application/json

{
    "email": "eumseo@icloud.com",
    "password" : "1234"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=eumseo@icloud.com&code=eCdgfS0DsI

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKTm1MaW1aK0xXSFJhcDBlNW8wVThHRGpMVk1JSFR4YWlvTGFtTEJ4YWpNPSIsImp0aSI6IkxaTDdacHN1elZWQUVieGVlMlQzalE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA1MTE5MTMsImV4cCI6MTY4MDU5ODMxM30.udJ7qWR_gjeJjlDx21NLjmXIDKtLiSGV32Xbmcdl5x8

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKTm1MaW1aK0xXSFJhcDBlNW8wVThHRGpMVk1JSFR4YWlvTGFtTEJ4YWpNPSIsImp0aSI6IkxaTDdacHN1elZWQUVieGVlMlQzalE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA1MTE5MTMsImV4cCI6MTY4MDU5ODMxM30.udJ7qWR_gjeJjlDx21NLjmXIDKtLiSGV32Xbmcdl5x8
Content-Type: application/json

{
    "from" : "server",
    "message" : "+points",
    "money" : 100000
}

####################

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth":"2022-03-26",
  "email" : "ieunseo415@gmail.com",
  "name" : "Test",
  "password" : "1234",
  "phone" : "01000000000"
}
### 로그인 (셀러)
POST http://localhost:8081/signIn/seller
Content-Type: application/json

{
    "email": "ieunseo415@gmail.com",
    "password" : "1234"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify?email=ieunseo415@gmail.com&code=mBaYen89jx
